import { z } from 'zod';

export const ConfigValidationSchema = z.object({
	ENV: z.string(),
	DB_NAME: z.string(),
	DB_HOST: z.string(),
	DB_PORT: z.string(),
	DB_USER: z.string(),
	DB_PASS: z.string(),
	APP_PORT: z.string(),
	CACHE_TTL: z.string(),
	URL_FRONT_WEB: z.string(),
	URL_FRONT_MOBILE: z.string(),
	SECRET_KEY: z.string(),
	JWT_EXPIRATION: z.string(),
	SECRET_KEY_REFRESH_TOKEN: z.string(),
	JWT_EXPIRATION_REFRESH_TOKEN: z.string(),
	DEFAULT_ADMIN_PASSWORD: z.string(),
	TWILIO_APP_SID: z.string(),
	TWILIO_SID: z.string(),
	TWILIO_AUTHTOKEN: z.string(),
	SENDGRID_API_KEY: z.string(),
	SENDGRID_EMAIL: z.string(),
	S3_ACCESS_KEY: z.string(),
	S3_SECRET_KEY: z.string(),
	S3_BUCKET_NAME: z.string(),
	S3_REGION: z.string(),
	SALT_ROUNDS: z.string(),
	TWILIO_EXPIRATION: z.string(),
	THROTTLE_LIMIT: z.string(),
	THROTTLE_TTL: z.string(),
	FIREBASE_CLIENT_EMAIL: z.string(),
	FIREBASE_PRIVATE_KEY: z.string(),
	FIREBASE_PROJECT_ID: z.string(),
});
