import { registerAs } from '@nestjs/config';

export default registerAs('ENV', () => ({
	env: process.env.ENV,
	db_name: process.env.DB_NAME,
	db_host: process.env.DB_HOST,
	db_port: process.env.DB_PORT,
	db_user: process.env.DB_USER,
	db_pass: process.env.DB_PASS,
	app_port: process.env.APP_PORT,
	url_front_web: process.env.URL_FRONT_WEB,
	url_front_mobile: process.env.URL_FRONT_MOBILE,
	secret_key: process.env.SECRET_KEY,
	jwt_expiration: process.env.JWT_EXPIRATION,
	secret_key_refresh: process.env.SECRET_KEY_REFRESH_TOKEN,
	jwt_expiration_refresh_token: process.env.JWT_EXPIRATION_REFRESH_TOKEN,
	default_admin_password: process.env.DEFAULT_ADMIN_PASSWORD,
	twilio_app_sid: process.env.TWILIO_APP_SID,
	twilio_sid: process.env.TWILIO_SID,
	twilio_authtoken: process.env.TWILIO_AUTHTOKEN,
	sendgrid_api_key: process.env.SENDGRID_API_KEY,
	sendgrid_email: process.env.SENDGRID_EMAIL,
	s3_access_key: process.env.S3_ACCESS_KEY,
	s3_secret_key: process.env.S3_SECRET_KEY,
	s3_bucket_name: process.env.S3_BUCKET_NAME,
	s3_region: process.env.S3_REGION,
	cache_ttl: process.env.CACHE_TTL,
	salt_rounds: process.env.SALT_ROUNDS,
	twilio_expiration: process.env.TWILIO_EXPIRATION,
	throttle_limit: process.env.THROTTLE_LIMIT,
	throttle_ttl: process.env.THROTTLE_TTL,
}));
