export enum NotificationTypes {
  TASK_CHANGE_STATUS = 'TASK_CHANGE_STATUS',
  TASK_ASSIGNATIONS = 'TASK_ASSIGNATIONS',
  TASK_REQUEST_APPOVED = 'TASK_REQUEST_APPOVED',
  TASK_NEW_MESSAGE = 'TASK_NEW_MESSAGE',
  NEW_REQUEST_TASK = 'NEW_REQUEST_TASK',
  TASK_RATING = 'TASK_RATING',
}
